/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://xxente4x6jfmnb3u42yle5hkee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-267hrvqxdfagdkbuwlmaiy7yei",
    "aws_cognito_identity_pool_id": "us-east-1:c68a59e3-65af-412a-9bb6-1b2bfdd751ac",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wkNY7H6Lr",
    "aws_user_pools_web_client_id": "1tk4kgfnf65cged6h7jgte0hoe",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
